using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SharpNinja.FeatureFlags.Generators;

/// <summary>
/// Roslyn incremental source generator that reads
/// <c>[assembly: ProductScope("productId")]</c> from the compiling assembly and emits
/// a <c>ProductScopeConstants</c> static class with a compile-time constant for the product ID.
/// </summary>
/// <remarks>
/// The emitted constant lets consuming code reference the product ID without magic strings,
/// and allows <c>flagctl</c> to read the product scope from assembly metadata.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class ProductScopeGenerator : IIncrementalGenerator
{
    private const string ProductScopeAttributeFullName =
        "SharpNinja.FeatureFlags.Abstractions.Attributes.ProductScopeAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Collect assembly-level ProductScopeAttribute arguments from the compiling assembly.
        IncrementalValueProvider<string?> productIdProvider =
            context.CompilationProvider.Select(static (compilation, _) =>
                ExtractProductId(compilation));

        // Generate only when a product ID is present.
        context.RegisterSourceOutput(productIdProvider, static (spc, productId) =>
        {
            if (productId is null)
            {
                return;
            }

            string source = GenerateProductScopeConstants(productId);
            spc.AddSource("ProductScopeConstants.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string? ExtractProductId(Compilation compilation)
    {
        INamedTypeSymbol? attrSymbol = compilation.GetTypeByMetadataName(ProductScopeAttributeFullName);
        if (attrSymbol is null)
        {
            return null;
        }

        foreach (AttributeData attr in compilation.Assembly.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, attrSymbol))
            {
                continue;
            }

            if (attr.ConstructorArguments.Length > 0
                && attr.ConstructorArguments[0].Value is string productId
                && !string.IsNullOrWhiteSpace(productId))
            {
                return productId.Trim();
            }
        }

        return null;
    }

    private static string GenerateProductScopeConstants(string productId)
    {
        // Escape any double-quote characters in the productId value for safe string literal embedding.
        string escaped = productId.Replace("\\", "\\\\").Replace("\"", "\\\"");

        return $@"// <auto-generated/>
// This file was generated by SharpNinja.FeatureFlags.Generators.ProductScopeGenerator.
// Do not edit this file manually.
#nullable enable

/// <summary>
/// Compile-time constants derived from the <c>[assembly: ProductScope]</c> attribute
/// applied to this assembly.
/// </summary>
internal static class ProductScopeConstants
{{
    /// <summary>The SharpNinja product identifier for this assembly.</summary>
    public const string ProductId = ""{escaped}"";
}}
";
    }
}
