using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SharpNinja.FeatureFlags.Generators;

/// <summary>
/// Roslyn incremental source generator that reads
/// <c>[assembly: ProductScope("productId")]</c> from the compiling assembly and emits
/// a <c>ProductScopeConstants</c> static class with a compile-time constant for the product ID.
/// </summary>
/// <remarks>
/// The emitted constant lets consuming code reference the product ID without magic strings,
/// and allows <c>flagctl</c> to read the product scope from assembly metadata.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class ProductScopeGenerator : IIncrementalGenerator
{
    private const string ProductScopeAttributeFullName =
        "SharpNinja.FeatureFlags.Abstractions.ProductScopeAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Collect assembly-level ProductScopeAttribute arguments from the compiling assembly.
        IncrementalValueProvider<string?> productIdProvider =
            context.CompilationProvider.Select(static (compilation, _) =>
                ExtractProductId(compilation));

        // Generate only when a product ID is present.
        context.RegisterSourceOutput(productIdProvider, static (spc, productId) =>
        {
            if (productId is null)
            {
                return;
            }

            string source = GenerateProductScopeConstants(productId);
            spc.AddSource("ProductScopeConstants.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string? ExtractProductId(Compilation compilation)
    {
        INamedTypeSymbol? attrSymbol = compilation.GetTypeByMetadataName(ProductScopeAttributeFullName);
        if (attrSymbol is null)
        {
            return null;
        }

        foreach (AttributeData attr in compilation.Assembly.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, attrSymbol))
            {
                continue;
            }

            // v1.0.3 widened the ctor to params string[]. ConstructorArguments[0]
            // is now a TypedConstant of kind Array whose Values element list holds
            // the product ids. Pick the first non-empty entry as the canonical
            // generated constant value (multi-product assemblies still expose a
            // single ProductScopeConstants.ProductId for back-compat).
            if (attr.ConstructorArguments.Length == 0)
            {
                continue;
            }

            TypedConstant firstArg = attr.ConstructorArguments[0];
            if (firstArg.Kind == TypedConstantKind.Array && !firstArg.Values.IsDefault)
            {
                foreach (TypedConstant element in firstArg.Values)
                {
                    if (element.Value is string id && !string.IsNullOrWhiteSpace(id))
                    {
                        return id.Trim();
                    }
                }
            }
            else if (firstArg.Value is string legacyId && !string.IsNullOrWhiteSpace(legacyId))
            {
                // Backward compat path for any caller still binding via the
                // v1.0.2 single-string ctor (covered by the params overload).
                return legacyId.Trim();
            }
        }

        return null;
    }

    private static string GenerateProductScopeConstants(string productId)
    {
        // Escape any double-quote characters in the productId value for safe string literal embedding.
        string escaped = productId.Replace("\\", "\\\\").Replace("\"", "\\\"");

        return $@"// <auto-generated/>
// This file was generated by SharpNinja.FeatureFlags.Generators.ProductScopeGenerator.
// Do not edit this file manually.
#nullable enable

/// <summary>
/// Compile-time constants derived from the <c>[assembly: ProductScope]</c> attribute
/// applied to this assembly.
/// </summary>
internal static class ProductScopeConstants
{{
    /// <summary>The SharpNinja product identifier for this assembly.</summary>
    public const string ProductId = ""{escaped}"";
}}
";
    }
}
